::będize::będzie
::bęzdie::będzie
::beiżący::bieżący
::jesli::jeśli
::jesłi::jeśli
::jeśłi::jeśli
::jeszze::jeszcze
::jets::jest
::kikla::kilka
::linicah::liniach
::moze::może
::mozę::może
::możę::może
::pred::przed
::rzaie::razie
::sie::się
::tylo::tylko
::włąśnie::właśnie
::wszytko::wszystko
::zaimana::zamiana
::zaisntalował::zainstalował
::zamaist::zamiast
::zasazdie::zasadzie
::żę::że
::zeby::żeby
::żęby::żeby
::zmaina::zmiana
::zmeiniła::zmieniła
:?c*:szzc::szcz
:?c*:szsy::szys
:?c*:łądn::ładn
